@startuml

actor Kunde
boundary "makeCarport.jsp" as MC
boundary "CmdCreateOrder.java" as CCO
boundary "specificUserOrders.jsp" as SO
participant "OrderMapper.java" as OM
database "Database" as DB

Kunde -> MC : Bestil
MC -> CCO : Opret ordre
CCO -> OM : Forbered Ordre
OM -> DB : Tilføj Ordre
DB -> OM : Hent Ordrer
OM -> SO : Forbered ordrer
SO -> Kunde : Fremvis ordrer

@enduml