@startuml

actor Kunde

boundary "index.jsp" as index

boundary "specificUserOrders.jsp" as suo

participant "CmdShowOrders.java" as cmd

participant "OrderMapper.java" as OM

database "Database" as DB


Kunde -> index : start
index -> cmd : Indtast email
cmd -> OM : Find ordre
OM -> DB : kig efter ordrer i databasen
DB -> OM : Retunerer ordre
OM -> cmd : Retunerer ordre
cmd -> cmd : Gemmer ordredata i atribut
cmd -> suo : Forward data og opbyg side
suo -> Kunde : vis ordre


@enduml