@startuml

actor Ansat
boundary "allOrders.jsp" as Orders
entity "Order Element" as OE
participant "RenderOrderInspect.java" as RO
participant "OrderMapper.java" as OM
database "Database" as DB

group Inspicer
Ansat -> OE : Inspicer Ordre 
OE -> RO : Render Ordre
RO -> Ansat : Fremvis Ordre
end

group Opdater
Ansat -> OE : Opdater Ordre
OE -> OM : DB Adgang
OM -> DB : Tilføj Opdatering
DB -> OM : Forespørg Odateret Ordre
OM -> Orders : Orderhistorik
Orders -> Ansat : Fremvis Ordre
end

@enduml
