@startuml

actor Ansat
boundary "allOrders.jsp" as AO
boundary "CmdPageUpdateOrder.java" as CUO
participant "OrderMapper.java" as OM
database "Database" as DB

Ansat -> CUO : Opdater ordre
CUO -> OM : DB adgang
OM -> DB : Tilføj opdatering
DB -> OM : Hent ordre
OM -> AO : Orderhistorik
AO -> Ansat : Fremvis ordre


@enduml