@startuml

actor Ansat
actor Ansat
boundary "allOrders.jsp" as Orders
entity "Order Element" as OE
participant "OrderMapper.java" as OM
database "Database" as DB

Ansat -> OE : Opdater Ordre
OE -> OM : DB Adgang
OM -> DB : Tilføj Opdatering
DB -> OM : Forespørg Odateret Ordre
OM -> Orders : Orderhistorik
Orders -> Ansat : Fremvis Ordre

@enduml