@startuml

actor Kunde
boundary "Order.jsp" as Order
boundary "ViewOrders.jsp" as Orders
participant "OrderMapper.java" as OM
database "Database" as DB

Kunde -> Order : Bestil
Order -> OM : DB Adgang
OM -> DB : Tilføj Ordre
DB -> OM : Hent Ordre
OM -> Orders : Alle Ordre
Orders -> Kunde : Orderhistorik

@enduml