@startuml

actor Kunde
boundary "ViewOrders.jsp" as Orders
entity "Order Element" as OE
participant "RenderOrder.java" as RO
participant "OrderMapper.java" as OM
database "Database" as DB

Kunde -> Orders : Forespørg Orderhistorik
Orders -> OM : DB Adgang
OM -> DB : Forespørg Ordre
DB -> OM : Hent Ordre
OM -> RO : Alle Ordre
RO -> Orders : Fremvis Ordre
Orders -> OE : Orderhistorik
OE -> Kunde : Order Detaljer

@enduml