@startuml

actor Kunde

boundary "index.jsp" as index

boundary "specificUserOrders.jsp" as suo

participant "CmdShowOrders.java" as cmd

participant "OrderMapper.java" as OM

database "Database" as DB


Kunde -> index : start
index -> cmd : Indtast email
cmd -> OM : Find ordrer
OM -> DB : kig efter ordrer i databasen
DB -> OM : Retunerer ordrer
OM -> cmd : Retunerer ordrer
cmd -> cmd : Gemmer ordrerdata i atribut
cmd -> suo : Forward data og opbyg side
suo -> Kunde : vis ordrer


@enduml