@startuml

actor Ansat
boundary "allOrders.jsp" as AO
boundary "ServletGetPartlist.java" as ajax
boundary "partlist.jsp" as PL


skinparam sequence {

    BoxBorderColor none
    BoxBackgroundColor whitesmoke

}

box "AJAX kald" 
participant ajax
participant PL
end box

Ansat -> AO : Gå til alle ordrer
AO -> Ansat : Vis alle ordrer
Ansat -> AO : Vælg ordre
AO -> ajax  : Ajax kald til servlet
ajax -> ajax: udregn stykliste
ajax -> PL  : forward stykliste
PL -> AO    : Udskriv stykliste
AO -> Ansat : Vis valgte ordre

@enduml