@startuml
|Kunde|
start
:Indtast email;
|#AntiqueWhite|System|
:Henter ordre for email;
:Vis ordre;
|Kunde|
:Vælg tab for tegning;
|#AntiqueWhite|System|
:Tegn carport;
|Kunde|
:Vælg tab for stykliste;
|#AntiqueWhite|System|
:Beregn stykliste;
|Kunde|
stop
@enduml
